### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Anooyman** [jiaqima/G3NN#1]
Hi,
I have ran the environment.yml file to create the env. However, I find this error ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'. I wonder if you have the solution of this error?

**Comment by jiaqima** [comment]
Hello Anooyman,

torch_scatter is a dependency of torch_geometric. Please see the following link for the official installation instruction: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
