### ISSUE TITLE
Resolve package not found

### ISSUE THREAD

**Issue by JialongWang1224** [jiaqima/G3NN#2]
您好，我用readme中的 conda torch_env create -f environment.yml不能安装，提示没有这个这个命令，只能用conda env create -f environment.yml，然后提示Resolve package not found，不知道z恩么解决呢？
![image](https://user-images.githubusercontent.com/30322251/103775827-8fd7ba00-5069-11eb-86fc-3da9e142d70c.png)

**Comment by jiaqima** [comment]
Hi! This seems to be a problem with the conda environment on your PC. Sorry I'm not an expert on conda and do not have a good solution to it. Perhaps you can go to the [Github page for conda](https://github.com/conda/conda) to see if you can find any solution.

Closing the issue for now.
